### ISSUE TITLE
Preventing Reserved Email Addresses

### ISSUE THREAD

**Issue by winduptoy** [larron/mongoose-email-address-manager#10]
Quick question regarding this system. How would I avoid the following conflict?

**USER A:**
Email 1: john@example.com (valid, he owns it)
Email 2: mark@example.com (he does not own it)

**USER B:**
Email 1: mark@example.com (valid, he owns it)

If User A signs up first and adds mark@example.com to his account (but doesn't verify), and then User B signs up with mark@example.com, then a query of `findOneByEmail` will return User A, leading us to believe that the email address has already been taken. Is there a recommended way of handling this scenario?

**Comment by larron** [comment]
@winduptoy Hey Matt, this scenario presents some interesting complications.  You would need to use the User.findByEmail and do some manual comparison to figure out what you wanted to do next.  Generally it's a better practice to disallow duplicate email addresses especially when you will use them for a login system.  It sucks for User B, but I'm sure he'd get along just fine with a different email.
