### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by raminsaf** [larron/mongoose-email-address-manager#6]
Hi Larron, thanks for a great package. I am having trouble installing it. Please advise.

[root]# npm install mongoose-email-address-manager
npm http GET https://registry.npmjs.org/mongoose-email-address-manager
npm http 304 https://registry.npmjs.org/mongoose-email-address-manager
npm http GET https://registry.npmjs.org/mongoose-email-address-manager/-/mongoose-email-address-manager-0.0.4.tgz
npm http 404 https://registry.npmjs.org/mongoose-email-address-manager/-/mongoose-email-address-manager-0.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/mongoose-email-address-manager/-/mongoose-email-address-manager-0.0.4.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/lib/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.1.2.0.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "mongoose-email-address-manager"
npm ERR! cwd /home/www-data/node
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.6
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/www-data/node/npm-debug.log
npm ERR! not ok code 0

**Comment by larron** [comment]
@raminsaf Sorry for the late response, this should be working now with 0.0.5.
